1. 0부터 9까지 정수를 가지는 NumPy 배열을 만들고 print 하세요

In [2]:
import numpy as np

a = np.arange(10)

print(a)

[0 1 2 3 4 5 6 7 8 9]


2. 위 배열을 (2, 5) 형태로 변경하고 print 하시오

In [3]:
import numpy as np

print(a.reshape(2, 5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


3. 다음 배열에서 두 번째 행만 출력하시오

[[1,2,3],    
 [4,5,6],    
 [7,8,9]]    

In [5]:
import numpy as np

a = np.arange(1, 10).reshape(3, -1)
print(a[1])

[4 5 6]


4. 위의 배열의 모든 값에 10을 더하고 print 하시오.

In [6]:
import numpy as np

print(a+10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


5. 다음 두 배열을 vstack으로 합치시오.   
A = np.array([1,2,3])   
B = np.array([4,5,6])   

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


6. arange, reshape을 이용하여 아래와 같은 배열 a를 만들고 print 하시오

[[0,1,2,3],  

 [4,5,6,7]]

In [11]:
import numpy as np

print(np.arange(8).reshape(2, -1))

[[0 1 2 3]
 [4 5 6 7]]


7. arange, reshape, concatenate를  이용하여 아래와 같은 배열 a를 만들고 print 하시오     
[[0,1,2],  
 [3,4,5],  
 [0,1,2],  
 [3,4,5]]  

In [12]:
a = np.arange(6).reshape(2, -1)

print(np.concatenate((a, a), axis=0))

[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
