1. arange, reshape, concatenate를 이용하여 다음 배열을 만들고 print 하시오.

[[0, 1, 0, 1],  
 [1, 0, 1, 0],  
 [0, 1, 0, 1],  
 [1, 0, 1, 0]]

In [9]:
import numpy as np

a = np.arange(4) % 2
b = np.arange(1, 5) % 2

a = a.reshape(1, 4)
b = b.reshape(1, 4)

print(np.concatenate((a, b, a, b), axis=0))

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


2. arange, reshape, concatenate를 이용하여 다음 배열을 만들고 print 하시오.

[[0, 1, 2, 0, 1, 2],  
 [3, 4, 5, 3, 4, 5],  
 [6, 7, 8, 6, 7, 8]]  


In [ ]:
import numpy as np

a = np.arange(6) % 3
a = a.reshape(1, 6)

b = a + 3
c = b + 3

print(np.concatenate((a, b, c), axis=0))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]


3. arange, reshape, concatenate를 이용하여 다음 배열을 만들고 print 하시오.


[[0, 1, 2, 3, 0, 1, 2, 3],  
 [4, 5, 6, 7, 4, 5, 6, 7],  
 [8, 9,10,11, 8, 9, 10, 11]]  

In [19]:
import numpy as np

a = np.arange(8) % 4
a = a.reshape(1, 8)

b = a + 4
c = b + 4

print(np.concatenate((a, b, c), axis=0))

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


4. arange, 와 reshape을 한 번씩 concatenate를 두 번 이용하여 다음 배열을 만들고  print 하시오.   
[[0, 1, 2, 0, 1, 2],    
 [3, 4, 5, 3, 4, 5],  
 [0, 1, 2, 0, 1, 2],  
 [3, 4, 5, 3, 4, 5]]  

In [9]:
import numpy as np

a = np.arange(6) % 3
a = a.reshape(1, 6)

b = a + 3

print(np.concatenate((a, b, a, b), axis=0))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


5. arange, reshape, concatenate를 이용하여 다음 배열을 만들고 print 하시오.   

[[ 0, 2, 4, 10, 12, 14],  
 [ 6, 8, 10, 16, 18, 20]]


In [11]:
import numpy as np

a = np.arange(0, 5, 2).reshape(1, 3)

b = np.arange(10, 15, 2).reshape(1, 3)


a = np.concatenate((a, a+6), axis=0)
b = np.concatenate((b, b+6), axis=0)

print(np.concatenate((a, b), axis=1))

[[ 0  2  4 10 12 14]
 [ 6  8 10 16 18 20]]


6. arange, reshape, concatenate를  이용하여 아래와 같은 배열을 만들고 print 하시오.  
[[1, 3, 5],  
[7, 9, 11],  
[20, 24, 28],  
[32, 36, 40]]  

In [12]:
import numpy as np

a = np.arange(1, 12, 2).reshape(2, -1)
b = np.arange(20, 41, 4).reshape(2, -1)

print(np.concatenate((a, b), axis=0))

[[ 1  3  5]
 [ 7  9 11]
 [20 24 28]
 [32 36 40]]
