다음 배열 a에서 각 행의 평균을 구한 결과 배열 b를 만들고 print하시오.

In [3]:
import numpy as np
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.mean(a, axis=1)
print(b)

[2. 5. 8.]


2.  다음과 같이 배열 a를 만들고 print하는 code를 작성하시오

[[1 1 1 1 1 1]  
 [1 0 0 0 0 1]  
 [1 0 0 0 0 1]  
 [1 0 0 0 0 1]  
 [1 0 0 0 0 1]  
 [1 1 1 1 1 1]]  

In [ ]:
import numpy as np
a = np.ones((6, 6))

a[1:5, 1:5] = 0
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


3. 다음 조건의 5×5 배열을 만드시오.

각 원소 a[i, j] = i + j  

[[0 1 2 3 4]  
 [1 2 3 4 5]  
 [2 3 4 5 6]  
 [3 4 5 6 7]  
 [4 5 6 7 8]]  


In [ ]:
import numpy as np



4. 다음 code에 정의된  a를 이용하여  아래 결과 배열 b를 만들고 print하시오.

[[ 4,  5,  6,  7],  
 [ 8,  9, 10, 11]]


In [8]:
import numpy as np

a = np.arange(16).reshape(4, 4)

b = a[1:3, :]
print(b)

[[ 4  5  6  7]
 [ 8  9 10 11]]


5. 다음 code의 배열 a에서 내부 영역만 slicing한 뒤,  
그 안에서 전체 평균보다 큰 값만 남기고,  
그 값들 중 최솟값은 제외한 나머지의 평균을 구하라.  



In [20]:
import numpy as np

a = np.arange(1, 26).reshape(5, 5)

b = a[1:4, 1:4]
b = b[b > b.mean()]
b = b[b != b.min()]
print(b.mean())

18.0


6. 다음 code에 정의된  a를 이용하여  아래 결과 배열 b를 만들고 print하시오.

[[ 0,  1],  
 [ 4,  5],  
 [ 8,  9]]  


In [21]:
import numpy as np

a = np.arange(40)

b = a.reshape(-1, 2)[:5:2, :]
print(b)

[[0 1]
 [4 5]
 [8 9]]


7. 다음 code에 정의된  a를 이용하여  아래 결과 배열 b를 만들고 print하시오.

[[ 1,  2,  3,  4,  5],  
 [11, 12, 13, 14, 15]]  

In [22]:
import numpy as np

a = np.arange(1, 51)

b = a.reshape(-1, 5)[:3:2, :]
print(b)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
