print(b)의 결과가 다음과 같이 되는 code를 작성하시오.  
b는 a를 이용하여 정의 함.   

1.   
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [ ]:
import numpy as np
a = np.arange(16)

b = a.reshape(1, 16)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


2.   
[  [ 0  1  2  3  4  5  6  7]  
   [ 8  9 10 11 12 13 14 15]  ]

In [3]:
import numpy as np
a = np.arange(16)

b = a.reshape(2, -1)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


3.
 
[ [ [ 0  1]  
    [ 2  3]  
    [ 4  5]  
    [ 6  7]  
    [ 8  9]  
    [10 11]  
    [12 13]  
    [14 15] ]  ]  

In [5]:
import numpy as np
a = np.arange(16)

b = a.reshape(8, -1)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


4. 

[ [[ 0]  
   [ 1]  
   [ 2]]  

 [ [ 3]  
   [ 4]  
   [ 5] ]  

 [ [ 6]  
   [ 7]  
   [ 8]  ]  

 [ [ 9]  
   [10]  
   [11] ] ]  


In [8]:
import numpy as np
a = np.arange(12)

b = a.reshape(4, 3, 1)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]


5. [8]  



In [11]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

b = a[1:2, 3]

print(b)

[8]
