print(b)의 결과가 다음과 같이 되는 code를 작성하시오.  
b는 a, a1, a2 를 이용하여 정의함.   
 , 유무는 신경 쓰지 말것

1. [[2., 2., 2., 5.],  
        [5., 5., 2., 5.],  
        [9., 5., 5., 2.]]  

In [1]:
import torch
a = torch.tensor([[[ 2., 2., 2., 5.]],
                  [[ 5., 5., 2., 5.]],
                  [[ 9., 5., 5., 2.]]])
b = a.squeeze()

print(b)

tensor([[2., 2., 2., 5.],
        [5., 5., 2., 5.],
        [9., 5., 5., 2.]])


2. [[[1., 2., 2.]],  
    [[3., 4., 4.]]]

In [2]:
import torch
a = torch.FloatTensor([[1, 2, 2],
                       [3, 4, 4]])

b = a.unsqueeze(0)
print(b)
print(b.size())

tensor([[[1., 2., 2.],
         [3., 4., 4.]]])
torch.Size([1, 2, 3])


3. [[ 1.,  3., 10., 12.],  
      [ 4.,  6., 13., 15.],  
      [ 7.,  9., 16., 18.]]  

In [4]:
import torch
a1 = torch.FloatTensor([[1, 3],
                        [4, 6],
                        [7, 9]])

a2 = torch.FloatTensor([[10, 12],
                        [13, 15],
                        [16, 18]])

b = torch.cat([a1, a2], dim = 1)

print(b)
print(b.size())

tensor([[ 1.,  3., 10., 12.],
        [ 4.,  6., 13., 15.],
        [ 7.,  9., 16., 18.]])
torch.Size([3, 4])


 4. [[[ 1.,  2.],  
      [ 3.,  4.],  
      [ 5.,  6.]],  
     [[10., 11.],  
      [12., 13.],  
      [14., 15.]]]   

In [5]:
import torch
a1 =  torch.FloatTensor([[1, 2],
                         [3, 4],
                         [5, 6]])

a2 = torch.FloatTensor([[10, 11],
                        [12, 13],
                        [14, 15]])

b = torch.stack([a1, a2], dim = 0)

print(b)
print(b.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[10., 11.],
         [12., 13.],
         [14., 15.]]])
torch.Size([2, 3, 2])


 5.   [[[ 1.,  2.],  
         [10., 11.]],  
        [[ 3.,  4.],  
         [12., 13.]],  
        [[ 5.,  6.],  
         [14., 15.]]]

In [9]:
import torch
a1 =  torch.FloatTensor([[1, 2],
                         [3, 4],
                         [5, 6]])

a2 = torch.FloatTensor([[10, 11],
                        [12, 13],
                        [14, 15]])

b = torch.stack([a1, a2], dim = 1)

print(b)
print(b.size())

tensor([[[ 1.,  2.],
         [10., 11.]],

        [[ 3.,  4.],
         [12., 13.]],

        [[ 5.,  6.],
         [14., 15.]]])
torch.Size([3, 2, 2])


6. [[ 1.,  3., 10., 12.],  
      [ 4.,  6., 13., 15.],   
      [ 3., 3., 3., 3.],   
      [ 7.,  9., 16., 18.]]  

In [7]:
import torch
a1 =  torch.FloatTensor([[1, 3, 10, 12],
                         [4, 6, 13, 15]])

a2 = torch.FloatTensor([[3, 3, 3, 3],
                        [7, 9, 16, 18]])

b = torch.cat([a1, a2], dim = 0)

print(b)
print(b.size())

tensor([[ 1.,  3., 10., 12.],
        [ 4.,  6., 13., 15.],
        [ 3.,  3.,  3.,  3.],
        [ 7.,  9., 16., 18.]])
torch.Size([4, 4])


7. [[[ 1.,  3., 10., 12.],    
   [ 4.,  6., 13., 15.]]]  


In [8]:
import torch
a = torch.FloatTensor([[1, 3, 10, 12],
                       [4, 6, 13, 15]])

b = a.unsqueeze(0)

print(b)
print(b.size())

tensor([[[ 1.,  3., 10., 12.],
         [ 4.,  6., 13., 15.]]])
torch.Size([1, 2, 4])
