아래 문자열 입력을 정수형으로 변경하고 print하는 code를 작성하시오.

In [ ]:
# 범주형 데이터 처리
# 입력 데이터에 범주형 데이터가 있을 때 머신러닝 모델이 이해할 수 있도록 숫자로 변환해야 함
import numpy as np
X = np.array(['apple','grape','melon','orange'])

# 정수형 인코딩
# 각 범주형 데이터에 고유한 정수값을 부여하는 방법
# sklearn의 LabelEncoder를 사용하여 정수형 인코딩을 수행
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

X = labelencoder.fit_transform(X)
print(X)

[0 1 2 3]


아래 문자열 입력을 원 핫 인코딩으로 변경하고 print하는 code를 작성하시오.

In [ ]:
import numpy as np
X = np.array(['apple','grape','melon','orange'])

# 원핫 인코딩
# 각 범주형 데이터에 고유한 정수값을 부여한 후, 해당 정수값을 이진 벡터로 변환
# 방법1: sklearn의 OneHotEncoder를 사용하여 원핫 인코딩을 수행
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()

X = onehotencoder.fit_transform(X.reshape(-1, 1)).toarray()
print(X)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


아래 class vector를 원 핫 인코딩으로 변경하고 print하는  code를 작성하시오.

In [4]:
from tensorflow import keras

class_vector =[8, 3, 2, 5]

# 원핫 인코딩
# 방법2: keras의 to_categorical 함수를 사용하여 원핫 인코딩을 수행
from tensorflow.keras.utils import to_categorical
output = to_categorical(class_vector)

print(output)

[[0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]]
