## Copying Arrays
---

In [1]:
import numpy as np

---
**View**

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[0, :]
b

array([1, 2, 3, 4])

In [7]:
b[0] = 100
b

array([100,   2,   3,   4])

In [8]:
a

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

---
**deep copy**

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b = a.copy() # np.copy(a)

b[0][0] = 100

a[0][0]

np.int64(1)