## Subsetting, Slicing, Indexing
---

In [1]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

---
**Subsetting**

In [3]:
a[2]

array([ 9, 10, 11, 12])

In [4]:
a[1, 2]

np.int64(7)

---
**Slicing**

In [6]:
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
a[0:2, 1]

array([2, 6])

In [10]:
a[:1]

array([[1, 2, 3, 4]])

In [12]:
# [1,:,:]와 같다
a[1,...]

array([5, 6, 7, 8])

In [13]:
a[ : : -1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

---
**Boolean Indexing**

In [ ]:
a[a < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a < 10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [ ]:
a = np.array([1, 2, 3 , 4, 5])

# 조건에 해당하는 원소의 인덱스 반환
np.where(a < 3)

(array([0, 1]),)