## Initial Placeholders
---

In [1]:
import numpy as np

In [ ]:
# numpy.zeros(shape, dtype=None, order='C')
a = np.zeros((5, 5))
print(a)

In [ ]:
# numpy.ones(shape, dtype=None, order='C')
a = np.ones((2, 3, 4), dtype=np.int16)
print(a)

In [ ]:
# numpy.arange(start, stop, dtype=None)
a = np.arange(1, 10, 2)
print(a)

In [2]:
# numpy.linspace(start, stop. num, ...)
a = np.linspace(0, 2, 9)
print(a)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
# numpy.full(shape, fill_value, dtype=None)
a = np.full((2, 2), 7)
print(a)

In [ ]:
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
a = np.eye(5)
print(a)

b = np.eye(5, M=10, k=5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#numpy.random.random(size=None)
a = np.random.random(5)
b = np.random.random((5, 5))
print(a, b, sep='\n')

[0.64022817 0.00587061 0.90778661 0.93569871 0.86887208]
[[0.88684954 0.36651916 0.62135158 0.45974467 0.88079011]
 [0.20227971 0.33682112 0.97317542 0.44353192 0.0450143 ]
 [0.67378616 0.10333612 0.61873383 0.34420222 0.27768512]
 [0.77677793 0.80327886 0.11340059 0.44186507 0.8770668 ]
 [0.78243105 0.36250173 0.97175633 0.28544945 0.36926471]]


In [ ]:
# numpy.empty(shape, dtype=None, order='C')
a = np.empty((5, 5))
print(a)