## Array Manipulation
---

In [14]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

---
**Transposing Array**

In [20]:
a.shape

(2, 4)

In [22]:
# 전치 행렬
# np.transpose(a)
# a.transpose()
b = a.T
b

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [23]:
b.shape

(4, 2)

---
**Changing Array Shape**

In [30]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [32]:
a.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# -1은 자동으로 맞춤
a.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

---
**Combining Arrays**

In [38]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [42]:
np.concatenate((a, b), axis=0)
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [43]:
np.concatenate((a, b), axis=1)
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

---
**newaxis**

In [46]:
# np.newaxis 차원 추가
# 기존 배열에 크기 1짜리 차원을 삽입

a = np.array([1, 2, 3])
a.shape

(3,)

In [48]:
a[:, np.newaxis] # shape: (3, 1)

array([[1],
       [2],
       [3]])

In [49]:
a[np.newaxis, :] # shape: (1, 3)

array([[1, 2, 3]])